### ISSUE TITLE
Moderation tools

### ISSUE THREAD

**Issue by WebFreak001** [dlang/dub-registry#368] opened 2018-07-14 10:28 UTC
There should be tools for admins (Ban Account, Shadow Ban Account, Delete Package), but also for users (Report Package, Report User)

As in the recent few cases of spammers (see e.g. #292) I think this is a much needed feature

**Comment by s-ludwig** [comment] 2018-12-16 20:04
See also #90

**Comment by MartinNowak** [comment] 2018-12-23 20:13
Closed as duplicate of #90

**Closed by MartinNowak** 2018-12-23 20:13 UTC
Labels: enhancement
