### ISSUE TITLE
Search sometimes doesn't bring searched package at first position

### ISSUE THREAD

**Issue by p0nce** [dlang/dub-registry#350] opened 2018-06-18 12:47 UTC
Example: http://code.dlang.org/search?q=colorize

the "colorize" package, which is an exact match, is 12 out of _many_ results.

**Comment by ohdatboi** [comment] 2018-07-11 14:03
Search is all over the place. For example, http://code.dlang.org/search?q=io
Package `io`, which is an exact match and has a score of 1.4 is no. *171* in the search results.

Top results have nothing to do with io:
1. mir-algorithm
2. dpq2 
3. dub
4. unit-threaded
5. gfm
6. derelict-sdl2
7. libdparse
8. requests
9. eventcore
10. vibe-d

As you can see, only eventcore ad vibe-d are related to io.

Clearly, search prefers packages with higher score a lot more than packages related to the search request.

**Comment by WebFreak001** [comment] 2018-07-11 16:44
_and I thought naming my package something generic was a good idea_

**Comment by ohdatboi** [comment] 2018-07-11 17:01
Speaking of which, I just registered http://d.dub.pm

It's impossible to find using search on the registry - registry just returns 404.
Even if somebody fixes that, it'd be almost impossible to find it among other packages which mention D in any way (practically, every package does that).
It's impossible to fetch it via dub because it is hosted on the GitLab.

**Comment by s-ludwig** [comment] 2018-12-05 20:37
I think what happens is that the MongoDB text index scores the fields of each package version separately, resulting in them being scored N times higher than they should (especially N times compared to the package name). Does anyone know whether that can somehow be fixed by changing the index, or if the document structure needs to be changed?

The other issue is that the primary sorting key currently is the rounded package score, while it should probably be weighted against the text score, so that "io" at least has a chance to come first.

**Comment by s-ludwig** [comment] 2018-12-05 20:39
The 500 error when searching for "d" or similar btw. is caused by the server erroring out due to the query exceeding the RAM limit. Adding `.limit(200)` fixes that.

**Comment by MartinNowak** [comment] 2018-12-23 19:58
I'd say this is a duplicate of #330 et.al. We definitely need a better search, without wanting to host our own lucene/elasticsearch though.
Right now we're mostly grouping by the quality of packages first and by their text-match second.

**Closed by MartinNowak** 2018-12-23 19:58 UTC
