### ISSUE TITLE
Searching for vox-d does not work

### ISSUE THREAD

**Issue by gizmomogwai** [dlang/dub-registry#498] opened 2021-05-20 20:51 UTC
the query https://code.dlang.org/search?q=vox-d leads for me to:
```
500 - Internal Server Error

Internal Server Error

Internal error information:
vibe.db.mongo.connection.MongoDriverException@/root/.dub/packages/vibe-d-0.9.3/vibe-d/mongodb/vibe/db/mongo/cursor.d(304): Query failed. Does the database exist?
----------------
??:? [0x55925ae6c0e5]
??:? [0x55925ae94226]
??:? [0x55925ae7709d]
/root/ldc2-1.24.0-linux-x86_64/bin/../import/std/exception.d:517 [0x55925a8c5a85]
/root/ldc2-1.24.0-linux-x86_64/bin/../import/std/exception.d:437 [0x55925a8b8185]
/root/.dub/packages/vibe-d-0.9.3/vibe-d/mongodb/vibe/db/mongo/cursor.d:304 [0x55925a91faad]
/mnt/c/Users/soenke/develop/0-dlang/dub-registry/source/app.d:462 [0x55925a920550]
/mnt/c/Users/soenke/develop/0-dlang/dub-registry/source/app.d:322 [0x55925a920377]
/mnt/c/Users/soenke/develop/0-dlang/dub-registry/source/app.d:367 [0x55925a948c86]
/root/.dub/packages/vibe-d-0.9.3/vibe-d/mongodb/vibe/db/mongo/cursor.d:233 [0x55925a91f59d]
/root/.dub/packages/vibe-d-0.9.3/vibe-d/mongodb/vibe/db/mongo/cursor.d:60 [0x55925a8429dd]
/root/ldc2-1.24.0-linux-x86_64/bin/../import/std/algorithm/iteration.d:615 [0x55925a947d78]
/root/ldc2-1.24.0-linux-x86_64/bin/../import/std/array.d:140 [0x55925a83d0f2]
/mnt/c/Users/soenke/develop/0-dlang/dub-registry/source/dubregistry/dbcontroller.d:333 [0x55925a820c00]
/mnt/c/Users/soenke/develop/0-dlang/dub-registry/source/dubregistry/registry.d:103 [0x55925a7c1e23]
/mnt/c/Users/soenke/develop/0-dlang/dub-registry/source/dubregistry/web.d:476 [0x55925a7c1d87]
/root/.dub/packages/vibe-d-0.9.3/vibe-d/web/vibe/web/web.d:1043 [0x55925a8704ba]
/root/.dub/packages/vibe-d-0.9.3/vibe-d/web/vibe/web/web.d:214 [0x55925a8700c3]
router.d:218 [0x55925acea764]
router.d:674 [0x55925acecf96]
router.d:607 [0x55925acea436]
router.d:211 [0x55925acea1ee]
server.d:2292 [0x55925acf280b]
server.d:253 [0x55925acf0c3e]
server.d:245 [0x55925acf04fd]
server.d:2048 [0x55925acfabde]
task.d:721 [0x55925addf725]
task.d:739 [0x55925addbf51]
task.d:446 [0x55925addb69b]
??:? [0x55925ae6d52a]
```

searchiing for quoted vox-d works. https://code.dlang.org/search?q=%22vox-d%22

**Comment by WebFreak001** [comment] 2021-05-20 22:13
duplicate of #490

**Closed by WebFreak001** 2021-05-20 22:13 UTC
