### ISSUE TITLE
Internal server error for some search results

### ISSUE THREAD

**Issue by Luhrel** [dlang/dub-registry#527] opened 2022-07-27 11:31 UTC
When searching something like `prefix-d` (`prefix` can be anything), the website returns an internal server error :
```
500 - Internal Server Error

Internal Server Error

Internal error information:
vibe.db.mongo.connection.MongoDriverException@../../vibe.d/mongodb/vibe/db/mongo/cursor.d(304): Query failed. Does the database exist?
----------------
??:? [0x563eeb1dba05]
??:? [0x563eeb207186]
??:? [0x563eeb1e65bf]
/home/soenke/ldc2-1.28.0-linux-x86_64/bin/../import/std/exception.d:517 [0x563eeaadb40b]
/home/soenke/ldc2-1.28.0-linux-x86_64/bin/../import/std/exception.d:437 [0x563eeaacc205]
../../vibe.d/mongodb/vibe/db/mongo/cursor.d:304 [0x563eeab990b6]
source/app.d:462 [0x563eeab99af6]
source/app.d:322 [0x563eeab99954]
source/app.d:367 [0x563eeabd716c]
../../vibe.d/mongodb/vibe/db/mongo/cursor.d:233 [0x563eeab98bba]
../../vibe.d/mongodb/vibe/db/mongo/cursor.d:60 [0x563eeaa57a1d]
/home/soenke/ldc2-1.28.0-linux-x86_64/bin/../import/std/algorithm/iteration.d:614 [0x563eeabd6278]
/home/soenke/ldc2-1.28.0-linux-x86_64/bin/../import/std/array.d:140 [0x563eeaa52b72]
source/dubregistry/dbcontroller.d:333 [0x563eeaa36d00]
source/dubregistry/registry.d:104 [0x563eea9d3cc3]
source/dubregistry/web.d:476 [0x563eea9d3c50]
../../vibe.d/web/vibe/web/web.d:1043 [0x563eeaa85dc5]
../../vibe.d/web/vibe/web/web.d:214 [0x563eeaa859f3]
../../vibe.d/http/vibe/http/router.d:218 [0x563eeb012478]
../../vibe.d/http/vibe/http/router.d:734 [0x563eeb014de2]
../../vibe.d/http/vibe/http/router.d:667 [0x563eeb012156]
../../vibe.d/http/vibe/http/router.d:211 [0x563eeb011f06]
../../vibe.d/http/vibe/http/server.d:2286 [0x563eeb01ac8d]
../../vibe.d/http/vibe/http/server.d:253 [0x563eeb018fb0]
../../vibe.d/http/vibe/http/server.d:245 [0x563eeb018850]
../../vibe.d/http/vibe/http/server.d:2043 [0x563eeb022dcb]
../../vibe-core/source/vibe/core/task.d:737 [0x563eeb153dc5]
../../vibe-core/source/vibe/core/task.d:755 [0x563eeb1504fb]
../../vibe-core/source/vibe/core/task.d:454 [0x563eeb14faea]
??:? [0x563eeb1dd82a]
```
This error doesn't append when searching `-d` or `prefix-dsuffix`.

To reproduce :
- Go to https://code.dlang.org/.
- Search for a package : `vibe-d` ([direct link](https://code.dlang.org/search?q=vibe-d)).
- Contemplate the error message.

**Comment by WebFreak001** [comment] 2022-07-28 15:09
duplicate of #490

**Closed by WebFreak001** 2022-07-28 15:09 UTC
