### ISSUE TITLE
No way to report broken package

### ISSUE THREAD

**Issue by zorael** [dlang/dub-registry#396] opened 2018-12-15 10:08 UTC
https://code.dlang.org/packages/discord-d is broken and the github link 404s, but I can find no way to report it.

**Comment by MartinNowak** [comment] 2018-12-23 20:12
At least we zero rate dead packages so they appear last in search results, could easily do sth. more visible.
Closed as duplicate of #368 and #90

**Closed by MartinNowak** 2018-12-23 20:12 UTC
Labels: enhancement
