### ISSUE TITLE
 There was an error including a specific symbol in the search string 

### ISSUE THREAD

**Issue by sdvcn** [dlang/dub-registry#513] opened 2021-10-20 05:07 UTC
The query string contains "-"

https://code.dlang.org/search?q=ffmpeg-d
-------------------------------------
500 - Internal Server Error

Internal Server Error

Internal error information:
vibe.db.mongo.connection.MongoDriverException@/root/.dub/packages/vibe-d-0.9.3/vibe-d/mongodb/vibe/db/mongo/cursor.d(304): Query failed. Does the database exist?
----------------
??:? [0x55673c8acb25]
??:? [0x55673c8d4c96]
??:? [0x55673c8b644f]
/root/ldc2-1.27.1-linux-x86_64/bin/../import/std/exception.d:517 [0x55673c1e086b]
/root/ldc2-1.27.1-linux-x86_64/bin/../import/std/exception.d:437 [0x55673c1d1d05]
/root/.dub/packages/vibe-d-0.9.3/vibe-d/mongodb/vibe/db/mongo/cursor.d:304 [0x55673c294fa6]
source/app.d:462 [0x55673c2959d6]
source/app.d:322 [0x55673c295834]
source/app.d:367 [0x55673c2d081c]
/root/.dub/packages/vibe-d-0.9.3/vibe-d/mongodb/vibe/db/mongo/cursor.d:233 [0x55673c294aba]
/root/.dub/packages/vibe-d-0.9.3/vibe-d/mongodb/vibe/db/mongo/cursor.d:60 [0x55673c1646ad]
/root/ldc2-1.27.1-linux-x86_64/bin/../import/std/algorithm/iteration.d:614 [0x55673c2cf9d8]
/root/ldc2-1.27.1-linux-x86_64/bin/../import/std/array.d:140 [0x55673c15f882]
source/dubregistry/dbcontroller.d:333 [0x55673c144b30]
source/dubregistry/registry.d:103 [0x55673c0ea5e3]
source/dubregistry/web.d:476 [0x55673c0ea570]
/root/.dub/packages/vibe-d-0.9.3/vibe-d/web/vibe/web/web.d:1043 [0x55673c18e645]
/root/.dub/packages/vibe-d-0.9.3/vibe-d/web/vibe/web/web.d:214 [0x55673c18e273]
root/.dub/packages/vibe-d-0.9.3/vibe-d/http/vibe/http/router.d:218 [0x55673c6ef05c]
root/.dub/packages/vibe-d-0.9.3/vibe-d/http/vibe/http/router.d:674 [0x55673c6f172b]
root/.dub/packages/vibe-d-0.9.3/vibe-d/http/vibe/http/router.d:607 [0x55673c6eed56]
root/.dub/packages/vibe-d-0.9.3/vibe-d/http/vibe/http/router.d:211 [0x55673c6eeb1f]
root/.dub/packages/vibe-d-0.9.3/vibe-d/http/vibe/http/server.d:2292 [0x55673c6f72a0]
root/.dub/packages/vibe-d-0.9.3/vibe-d/http/vibe/http/server.d:253 [0x55673c6f5707]
root/.dub/packages/vibe-d-0.9.3/vibe-d/http/vibe/http/server.d:245 [0x55673c6f4fd5]
root/.dub/packages/vibe-d-0.9.3/vibe-d/http/vibe/http/server.d:2048 [0x55673c6ff0eb]
../../vibe-core/source/vibe/core/task.d:743 [0x55673c802ad5]
../../vibe-core/source/vibe/core/task.d:761 [0x55673c7ff25b]
../../vibe-core/source/vibe/core/task.d:449 [0x55673c7fe9b9]
??:? [0x55673c8adfaa]

**Comment by Geod24** [comment] 2021-10-20 05:12
Duplicate of https://github.com/dlang/dub-registry/issues/490

**Closed by Geod24** 2021-10-20 05:12 UTC
