### ISSUE TITLE
Gitlab dependencies result in server crash

### ISSUE THREAD

**Issue by wilzbach** [dlang/dub-registry#436] opened 2019-08-10 15:22 UTC
https://code.dlang.org/packages/silly/0.8.2.zip -> directly leads to a server crash (502)

See also: https://code.dlang.org/packages/silly

**Comment by AntonMeep** [comment] 2019-08-24 13:31
Can confirm. There aren't any logs or error messages, it just dies for a moment and then gets back up.
Could be an issue with GitLab credentials.

Related issue for silly: https://gitlab.com/AntonMeep/silly/issues/28

**Comment by AntonMeep** [comment] 2019-08-24 13:32
Full `dub fetch` log:
```
$ dub fetch silly --version=0.8.2 -v
Using dub registry url 'https://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/antonmeep/.dub/packages/local-packages.json
No valid package found in current working directory: No package file found in /home/antonmeep/, expected one of dub.json/dub.sdl/package.json
Fetching silly 0.8.2...
Package supplier registry at https://code.dlang.org/ failed with 'Failed to download package silly from https://code.dlang.org/packages/silly/0.8.2.zip', trying fallbacks.
Fallback package supplier registry at https://code-mirror.dlang.io/ failed with 'Failed to download https://code-mirror.dlang.io/api/packages/infos?packages=%5B%22silly%22%5D&include_dependencies=true&minimize=true'.
Fallback package supplier registry at https://dub-registry.herokuapp.com/ failed with 'HTTP request returned status code 503 (Service Unavailable)'.
Failed to download package silly from https://code.dlang.org/packages/silly/0.8.2.zip
```

**Comment by aliak00** [comment] 2019-10-10 13:58
Has anyone checked out what's the cause of the crash for gitlab deps?

**Comment by ErnyTech** [comment] 2019-10-12 22:17
I think this unpleasant issue is caused by the change of APIs to download the archive from GitLab (https://gitlab.com/gitlab-com/support-forum/issues/4154)

Now you need to use this: https://docs.gitlab.com/ee/api/repositories.html#get-file-archive

**Comment by ErnyTech** [comment] 2019-10-19 15:11
I sent a PR: https://github.com/dlang/dub-registry/pull/443

**Comment by ErnyTech** [comment] 2019-10-20 20:30
The PR has been combined in master and the version of dub-registry hosted on herokuapp is working properly, just try https://dub-registry-staging.herokuapp.com/packages/gitlab-test-package-erny/~master.zip !

I don't know when code.dlang.org will also be updated, but finally this issue is about to be closed!

**Comment by s-ludwig** [comment] 2019-10-21 16:08
The current master was deployed on code.dland.org now and gitlab-test-package seems to work, too!

**Comment by s-ludwig** [comment] 2019-10-21 19:26
Actually it still crashes when downloading the package, I just tested the version update.

**Comment by ErnyTech** [comment] 2019-10-21 19:31
In the version of herokuapp it works really well

**Comment by s-ludwig** [comment] 2019-10-22 09:16
I cleared it, but unfortunately that didn't help. A very brief inspection showed a segmentation fault when accessing `data` returned by `URLCache` through the callback at line 155. Is that the same crash as for the original issue?

**Comment by s-ludwig** [comment] 2019-11-23 16:27
I finally found the cause for the isse and pushed a fix: https://github.com/dlang/dub-registry/pull/447

**Closed** 2019-11-23 22:25 UTC
