### ISSUE TITLE
Detect new releases using web hooks

### ISSUE THREAD

**Issue by BBasile** [dlang/dub-registry#275] opened 2018-02-04 11:58 UTC
A trail to explore, of course when possible. This would not eliminate the need for the current system but for people accepting the hook they could have a faster detection. This can be useful when updating dependencies.

**Comment by s-ludwig** [comment] 2018-02-04 12:38
Definitely! We have avoided the absolute need for this up to now by optimizing the polling mechanism, but it really is overdue to use a more efficient approach. It may also makes sense to (soft) force new users/projects to connect with OAuth.

This is actually a duplicate of #10, so I'm closing this one.

**Closed by s-ludwig** 2018-02-04 12:38 UTC
